// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LPAREN-0]
	_ = x[RPAREN-1]
	_ = x[LBRACE-2]
	_ = x[RBRACE-3]
	_ = x[LSQR-4]
	_ = x[RSQR-5]
	_ = x[COMMA-6]
	_ = x[DOT-7]
	_ = x[MINUS-8]
	_ = x[PLUS-9]
	_ = x[SEMICOLON-10]
	_ = x[COLON-11]
	_ = x[SLASH-12]
	_ = x[STAR-13]
	_ = x[BANG-14]
	_ = x[NEQ-15]
	_ = x[EQ-16]
	_ = x[EQ_EQ-17]
	_ = x[GT-18]
	_ = x[GT_EQ-19]
	_ = x[LT-20]
	_ = x[LT_EQ-21]
	_ = x[IDENTIFIER-22]
	_ = x[STRING-23]
	_ = x[NUMBER-24]
	_ = x[AND-25]
	_ = x[BREAK-26]
	_ = x[CLASS-27]
	_ = x[CONTINUE-28]
	_ = x[CONST-29]
	_ = x[ELSE-30]
	_ = x[FALSE-31]
	_ = x[FOR-32]
	_ = x[FUN-33]
	_ = x[IF-34]
	_ = x[NIL-35]
	_ = x[OR-36]
	_ = x[PRINT-37]
	_ = x[RETURN-38]
	_ = x[SUPER-39]
	_ = x[THIS-40]
	_ = x[TRUE-41]
	_ = x[VAR-42]
	_ = x[WHILE-43]
	_ = x[EOF-44]
	_ = x[NUM_TOKENS-45]
}

const _TokenType_name = "LPARENRPARENLBRACERBRACELSQRRSQRCOMMADOTMINUSPLUSSEMICOLONCOLONSLASHSTARBANGNEQEQEQ_EQGTGT_EQLTLT_EQIDENTIFIERSTRINGNUMBERANDBREAKCLASSCONTINUECONSTELSEFALSEFORFUNIFNILORPRINTRETURNSUPERTHISTRUEVARWHILEEOFNUM_TOKENS"

var _TokenType_index = [...]uint8{0, 6, 12, 18, 24, 28, 32, 37, 40, 45, 49, 58, 63, 68, 72, 76, 79, 81, 86, 88, 93, 95, 100, 110, 116, 122, 125, 130, 135, 143, 148, 152, 157, 160, 163, 165, 168, 170, 175, 181, 186, 190, 194, 197, 202, 205, 215}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
