// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LPAREN-0]
	_ = x[RPAREN-1]
	_ = x[LBRACE-2]
	_ = x[RBRACE-3]
	_ = x[LSQR-4]
	_ = x[RSQR-5]
	_ = x[COMMA-6]
	_ = x[DOT-7]
	_ = x[MINUS-8]
	_ = x[PLUS-9]
	_ = x[SEMICOLON-10]
	_ = x[COLON-11]
	_ = x[SLASH-12]
	_ = x[STAR-13]
	_ = x[BANG-14]
	_ = x[NEQ-15]
	_ = x[EQ-16]
	_ = x[EQ_EQ-17]
	_ = x[GT-18]
	_ = x[GT_EQ-19]
	_ = x[LT-20]
	_ = x[LT_EQ-21]
	_ = x[IDENTIFIER-22]
	_ = x[STRING-23]
	_ = x[NUMBER-24]
	_ = x[AND-25]
	_ = x[BREAK-26]
	_ = x[CLASS-27]
	_ = x[CONTINUE-28]
	_ = x[ELSE-29]
	_ = x[FALSE-30]
	_ = x[FOR-31]
	_ = x[FUN-32]
	_ = x[IF-33]
	_ = x[NIL-34]
	_ = x[OR-35]
	_ = x[PRINT-36]
	_ = x[RETURN-37]
	_ = x[SUPER-38]
	_ = x[THIS-39]
	_ = x[TRUE-40]
	_ = x[VAR-41]
	_ = x[WHILE-42]
	_ = x[EOF-43]
}

const _TokenType_name = "LPARENRPARENLBRACERBRACELSQRRSQRCOMMADOTMINUSPLUSSEMICOLONCOLONSLASHSTARBANGNEQEQEQ_EQGTGT_EQLTLT_EQIDENTIFIERSTRINGNUMBERANDBREAKCLASSCONTINUEELSEFALSEFORFUNIFNILORPRINTRETURNSUPERTHISTRUEVARWHILEEOF"

var _TokenType_index = [...]uint8{0, 6, 12, 18, 24, 28, 32, 37, 40, 45, 49, 58, 63, 68, 72, 76, 79, 81, 86, 88, 93, 95, 100, 110, 116, 122, 125, 130, 135, 143, 147, 152, 155, 158, 160, 163, 165, 170, 176, 181, 185, 189, 192, 197, 200}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
